/**
 * Index Generator - Create index.md for spread results
 *
 * Generates comprehensive index file that summarizes all specialist
 * work and provides navigation.
 *
 * @module output/index-generator
 */

import * as fs from 'fs/promises';
import type {
  SpreadConfig,
  SpecialistResult,
  IndexMetadata,
} from '../types/index.js';

/**
 * Index generation options
 */
export interface IndexGeneratorOptions {
  includeFullSummaries?: boolean;
  includeTimestamps?: boolean;
  includeNavigation?: boolean;
  addNextSteps?: boolean;
}

/**
 * Index Generator
 *
 * Creates index.md files for spread results.
 */
export class IndexGenerator {
  private options: Required<IndexGeneratorOptions>;

  constructor(options: IndexGeneratorOptions = {}) {
    this.options = {
      includeFullSummaries: options.includeFullSummaries ?? true,
      includeTimestamps: options.includeTimestamps ?? true,
      includeNavigation: options.includeNavigation ?? true,
      addNextSteps: options.addNextSteps ?? true,
    };
  }

  /**
   * Generate and write index file
   *
   * @param config - Spread configuration
   * @param results - Specialist results
   * @param outputDir - Output directory
   * @param summary - Overall summary
   */
  async writeIndex(
    config: SpreadConfig,
    results: SpecialistResult[],
    outputDir: string,
    summary?: string
  ): Promise<void> {
    const metadata: IndexMetadata = {
      title: this.generateTitle(config.request),
      date: new Date(),
      request: config.request,
      specialistCount: results.length,
      status: this.determineStatus(results) as any,
      totalTokens: results.reduce((sum, r) => sum + r.tokensUsed, 0),
      duration: results.reduce((sum, r) => sum + r.duration, 0),
    };

    const content = this.formatIndex(config, results, metadata, summary);
    const filepath = `${outputDir}/index.md`;

    await fs.writeFile(filepath, content, 'utf-8');
  }

  /**
   * Format index content
   */
  private formatIndex(
    _config: SpreadConfig,
    results: SpecialistResult[],
    metadata: IndexMetadata,
    summary?: string
  ): string {
    const lines: string[] = [];

    // Title and metadata
    lines.push(`# Spread: ${metadata.title}`);
    lines.push('');

    if (this.options.includeTimestamps) {
      lines.push(`**Date:** ${metadata.date.toISOString()}`);
    }

    lines.push(`**Request:** ${metadata.request}`);
    lines.push(`**Specialists:** ${metadata.specialistCount}`);
    lines.push(`**Status:** ${this.formatStatus(metadata.status)}`);
    lines.push(`**Total Tokens:** ${metadata.totalTokens.toLocaleString()}`);
    lines.push(`**Duration:** ${(metadata.duration / 1000).toFixed(1)} seconds`);
    lines.push('');

    // Overview section
    lines.push('## Overview');
    lines.push('');

    const overview = this.generateOverview(results);
    lines.push(overview);
    lines.push('');

    // Specialists section
    lines.push('## Specialists');
    lines.push('');

    for (let i = 0; i < results.length; i++) {
      const result = results[i];
      const filename = this.generateFilename(result, i + 1);

      lines.push(`### ${i + 1}. ${this.toTitleCase(result.role)}`);
      lines.push('');

      if (this.options.includeNavigation) {
        lines.push(`📄 [View Full Output](${filename})`);
        lines.push('');
      }

      lines.push(`**Status:** ${this.formatSpecialistStatus(result.status)}`);
      lines.push(`**Tokens:** ${result.tokensUsed.toLocaleString()}`);
      lines.push(`**Duration:** ${(result.duration / 1000).toFixed(1)}s`);
      lines.push('');

      if (this.options.includeFullSummaries) {
        lines.push('**Summary:**');
        lines.push(result.summary);
        lines.push('');
      }
    }

    // Key insights section
    if (this.options.includeFullSummaries) {
      lines.push('## Key Insights');
      lines.push('');
      const insights = this.extractKeyInsights(results);
      insights.forEach(insight => {
        lines.push(`- ${insight}`);
      });
      lines.push('');
    }

    // Overall summary if provided
    if (summary) {
      lines.push('## Summary');
      lines.push('');
      lines.push(summary);
      lines.push('');
    }

    // Next steps
    if (this.options.addNextSteps) {
      lines.push('## Next Steps');
      lines.push('');
      const nextSteps = this.generateNextSteps(results);
      nextSteps.forEach(step => {
        lines.push(`1. ${step}`);
      });
      lines.push('');
    }

    // Footer
    lines.push('---');
    lines.push('');
    lines.push('*Generated by [Spreader Tool](https://github.com/SuperInstance/Spreader-tool) v1.0.0*');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Generate title from request
   */
  private generateTitle(request: string): string {
    const maxLength = 60;
    const truncated = request.length > maxLength
      ? request.substring(0, maxLength) + '...'
      : request;

    // Capitalize first letter
    return truncated.charAt(0).toUpperCase() + truncated.slice(1);
  }

  /**
   * Determine overall status from results
   */
  private determineStatus(results: SpecialistResult[]): string {
    const allSuccess = results.every(r => r.status === 'success');
    const anySuccess = results.some(r => r.status === 'success');

    if (allSuccess) return 'completed';
    if (anySuccess) return 'partial';
    return 'failed';
  }

  /**
   * Format status with emoji
   */
  private formatStatus(status: string): string {
    switch (status) {
      case 'completed':
        return '✅ Complete';
      case 'partial':
        return '⚠️ Partial';
      case 'failed':
        return '❌ Failed';
      default:
        return status;
    }
  }

  /**
   * Format specialist status
   */
  private formatSpecialistStatus(status: string): string {
    switch (status) {
      case 'success':
        return '✅ Success';
      case 'error':
        return '❌ Error';
      case 'cancelled':
        return '⚠️ Cancelled';
      default:
        return status;
    }
  }

  /**
   * Generate overview text
   */
  private generateOverview(results: SpecialistResult[]): string {
    const lines: string[] = [];

    const successCount = results.filter(r => r.status === 'success').length;
    const totalTokens = results.reduce((sum, r) => sum + r.tokensUsed, 0);
    const avgDuration = results.reduce((sum, r) => sum + r.duration, 0) / results.length;

    lines.push(`This spread involved ${results.length} specialist agents working in parallel.`);
    lines.push('');
    lines.push(`- **Completed:** ${successCount}/${results.length} specialists`);
    lines.push(`- **Total tokens:** ${totalTokens.toLocaleString()}`);
    lines.push(`- **Average duration:** ${(avgDuration / 1000).toFixed(1)}s per specialist`);
    lines.push('');

    if (successCount === results.length) {
      lines.push('All specialists completed successfully. Review individual outputs for detailed findings.');
    } else if (successCount > 0) {
      lines.push('Some specialists completed successfully. Review individual outputs for details and any errors.');
    } else {
      lines.push('All specialists failed. Review error messages in individual outputs.');
    }

    return lines.join('\n');
  }

  /**
   * Extract key insights from all results
   */
  private extractKeyInsights(results: SpecialistResult[]): string[] {
    const insights: string[] = [];

    for (const result of results) {
      if (result.status === 'success' && result.summary) {
        // Extract first sentence or key point
        const firstSentence = result.summary.split('.')[0];
        if (firstSentence.length > 20 && firstSentence.length < 200) {
          insights.push(`**${this.toTitleCase(result.role)}:** ${firstSentence}.`);
        }
      }
    }

    return insights;
  }

  /**
   * Generate next steps
   */
  private generateNextSteps(results: SpecialistResult[]): string[] {
    const steps: string[] = [];

    const allSuccess = results.every(r => r.status === 'success');

    if (allSuccess) {
      steps.push('Review all specialist outputs in detail');
      steps.push('Synthesize findings from multiple perspectives');
      steps.push('Identify actionable insights and recommendations');
      steps.push('Plan follow-up tasks based on findings');
    } else {
      steps.push('Review error messages from failed specialists');
      steps.push('Re-run failed specialists if needed');
      steps.push('Adjust configuration based on errors');
    }

    steps.push('Archive results for future reference');
    steps.push('Share findings with stakeholders if applicable');

    return steps;
  }

  /**
   * Generate filename for specialist
   */
  private generateFilename(result: SpecialistResult, index: number): string {
    const padded = index.toString().padStart(2, '0');
    const role = result.role.toLowerCase().replace(/[^a-z0-9]/g, '-');
    return `specialist-${padded}-${role}.md`;
  }

  /**
   * Convert to title case
   */
  private toTitleCase(str: string): string {
    return str
      .toLowerCase()
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  /**
   * Set generation options
   */
  setOptions(options: Partial<IndexGeneratorOptions>): void {
    this.options = { ...this.options, ...options };
  }

  /**
   * Get current options
   */
  getOptions(): Required<IndexGeneratorOptions> {
    return { ...this.options };
  }
}
