/**
 * Markdown Writer - Output specialist results as markdown
 *
 * Formats and writes specialist results to organized markdown files.
 *
 * @module output/markdown-writer
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import type {
  SpecialistResult,
  MarkdownFormatOptions,
} from '../types/index.js';

/**
 * Default format options
 */
const DEFAULT_FORMAT_OPTIONS: MarkdownFormatOptions = {
  includeTimestamps: true,
  includeMetadata: true,
  includeContext: true,
  includeSummary: true,
  pretty: true,
};

/**
 * Markdown Writer
 *
 * Formats and writes specialist results to markdown files.
 */
export class MarkdownWriter {
  private formatOptions: MarkdownFormatOptions;

  constructor(options?: Partial<MarkdownFormatOptions>) {
    this.formatOptions = { ...DEFAULT_FORMAT_OPTIONS, ...options };
  }

  /**
   * Write specialist result to markdown file
   *
   * @param result - Specialist result
   * @param outputDir - Output directory
   * @param index - Specialist index for filename
   * @returns File path
   */
  async writeSpecialistResult(
    result: SpecialistResult,
    outputDir: string,
    index: number
  ): Promise<string> {
    // Ensure output directory exists
    await fs.mkdir(outputDir, { recursive: true });

    // Generate filename
    const filename = this.generateFilename(result, index);
    const filepath = path.join(outputDir, filename);

    // Format markdown content
    const content = this.formatSpecialistMarkdown(result);

    // Write file
    await fs.writeFile(filepath, content, 'utf-8');

    return filepath;
  }

  /**
   * Write all specialist results
   *
   * @param results - Array of specialist results
   * @param outputDir - Output directory
   * @returns Array of file paths
   */
  async writeAllSpecialistResults(
    results: SpecialistResult[],
    outputDir: string
  ): Promise<string[]> {
    const filepaths: string[] = [];

    for (let i = 0; i < results.length; i++) {
      const filepath = await this.writeSpecialistResult(results[i], outputDir, i + 1);
      filepaths.push(filepath);
    }

    return filepaths;
  }

  /**
   * Format specialist result as markdown
   *
   * @param result - Specialist result
   * @returns Markdown content
   */
  formatSpecialistMarkdown(result: SpecialistResult): string {
    const lines: string[] = [];

    // Header
    lines.push('# Specialist: ' + this.toTitleCase(result.role));
    lines.push('');

    // Metadata section
    if (this.formatOptions.includeMetadata) {
      lines.push('## Metadata');
      lines.push('');
      lines.push(`**Role:** ${result.role}`);
      lines.push(`**Status:** ${this.formatStatus(result.status)}`);
      lines.push(`**Specialist ID:** ${result.specialistId}`);

      if (this.formatOptions.includeTimestamps) {
        lines.push(`**Timestamp:** ${result.timestamp.toISOString()}`);
      }

      lines.push(`**Tokens Used:** ${result.tokensUsed.toLocaleString()}`);
      lines.push(`**Duration:** ${(result.duration / 1000).toFixed(2)} seconds`);
      lines.push('');

      if (result.error) {
        lines.push(`**Error:** ${result.error}`);
        lines.push('');
      }
    }

    // Summary section
    if (this.formatOptions.includeSummary && result.summary) {
      lines.push('## Summary');
      lines.push('');
      lines.push(result.summary);
      lines.push('');
    }

    // Content section
    lines.push('## Full Output');
    lines.push('');
    lines.push(result.content);
    lines.push('');

    // Footer
    lines.push('---');
    lines.push('');
    lines.push(`*Generated by Spreader v1.0.0*`);

    return lines.join('\n');
  }

  /**
   * Generate filename for specialist result
   *
   * @param result - Specialist result
   * @param index - Specialist index
   * @returns Filename
   */
  private generateFilename(result: SpecialistResult, index: number): string {
    const padded = index.toString().padStart(2, '0');
    const role = result.role.toLowerCase().replace(/[^a-z0-9]/g, '-');
    return `specialist-${padded}-${role}.md`;
  }

  /**
   * Format status with emoji
   */
  private formatStatus(status: string): string {
    switch (status) {
      case 'success':
        return '✅ Success';
      case 'error':
        return '❌ Error';
      case 'cancelled':
        return '⚠️ Cancelled';
      default:
        return status;
    }
  }

  /**
   * Convert to title case
   */
  private toTitleCase(str: string): string {
    return str
      .toLowerCase()
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  /**
   * Write error report
   *
   * @param error - Error message
   * @param outputDir - Output directory
   * @returns File path
   */
  async writeErrorReport(error: string, outputDir: string): Promise<string> {
    await fs.mkdir(outputDir, { recursive: true });

    const filepath = path.join(outputDir, 'error-report.md');
    const content = this.formatErrorReport(error);

    await fs.writeFile(filepath, content, 'utf-8');

    return filepath;
  }

  /**
   * Format error report
   */
  private formatErrorReport(error: string): string {
    const lines: string[] = [];

    lines.push('# Error Report');
    lines.push('');
    lines.push(`**Timestamp:** ${new Date().toISOString()}`);
    lines.push('');
    lines.push('## Error Details');
    lines.push('');
    lines.push('```');
    lines.push(error);
    lines.push('```');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Set format options
   */
  setFormatOptions(options: Partial<MarkdownFormatOptions>): void {
    this.formatOptions = { ...this.formatOptions, ...options };
  }

  /**
   * Get current format options
   */
  getFormatOptions(): MarkdownFormatOptions {
    return { ...this.formatOptions };
  }
}
